-- Fix lesson content to match @kidspark/shared content-schema types
-- Story: type=story, character{name,avatar_key,personality}, pages[{id,narration,character_dialogue,age_variants}]
-- Quiz:  type=quiz, character, questions[{id,question,question_type,options[{id,text}],correct_answer,explanation,hints,points}]
-- Sandbox: type=sandbox, character, sandbox_type, hints, items[{id,label,correct_zone_id}], zones[{id,label,accepts}], completion_criteria

UPDATE lessons SET content_json = '{"type":"story","character":{"name":"Rexy","avatar_key":"","personality":"friendly"},"pages":[{"id":"p1","narration":"Meet Rexy the T-Rex!","character_dialogue":"ROARRR! Hi! I am Rexy!","age_variants":{"3-5":{"narration":"Meet Rexy! Big teeth tiny arms!"},"6-8":{"narration":"T-Rex was the king of dinosaurs!"},"9-12":{"narration":"T. rex dominated the Late Cretaceous."}}},{"id":"p2","narration":"T-Rex arms cannot reach their own mouth!","character_dialogue":"Tiny arms huge power!","age_variants":{"3-5":{"narration":"Teeny tiny arms!"},"6-8":{"narration":"40ft body 3ft arms."},"9-12":{"narration":"Disproportionately small forelimbs."}}},{"id":"p3","narration":"Over 50 teeth each up to 8 inches long!","character_dialogue":"My teeth crunch bone!","age_variants":{"3-5":{"narration":"50 big teeth! Crunch crunch!"},"6-8":{"narration":"Strongest bite force ever recorderd."},"9-12":{"narration":"35000+ N bite force confirmed by coprolites."}}},{"id":"p4","narration":"Lived 66 million years ago. Birds are their relatives!","character_dialogue":"Find my bones in museums!","age_variants":{"3-5":{"narration":"Way before grandparents!"},"6-8":{"narration":"Extinct 66 Mya. Birds evolved from them!"},"9-12":{"narration":"Chicxulub K-Pg event. Avian lineages survived."}}}]}', updated_at = datetime('now') WHERE id = 1;

UPDATE lessons SET content_json = '{"type":"quiz","character":{"name":"Rexy","avatar_key":"","personality":"encouraging"},"passing_score":3,"completion_message":"Great job!","questions":[{"id":"q1","question":"What did T-Rex eat?","question_type":"multiple_choice","options":[{"id":"a","text":"Plants"},{"id":"b","text":"Meat"},{"id":"c","text":"Fish only"},{"id":"d","text":"Seeds"}],"correct_answer":"b","explanation":"T-Rex was a carnivore!","hints":{"3-5":"Sharp teeth!","6-8":"Teeth shape clue.","9-12":"Dentition morphology."},"points":1},{"id":"q2","question":"How long ago did T-Rex live?","question_type":"multiple_choice","options":[{"id":"a","text":"100 years ago"},{"id":"b","text":"1 million years ago"},{"id":"c","text":"66 million years ago"},{"id":"d","text":"A billion years ago"}],"correct_answer":"c","explanation":"66 million years ago.","hints":{"3-5":"Very long ago!","6-8":"Think millions.","9-12":"End of Cretaceous."},"points":1},{"id":"q3","question":"T-Rex had very short...?","question_type":"multiple_choice","options":[{"id":"a","text":"Legs"},{"id":"b","text":"Arms"},{"id":"c","text":"Tail"},{"id":"d","text":"Neck"}],"correct_answer":"b","explanation":"Tiny arms!","hints":{"3-5":"Cannot reach mouth!","6-8":"Tiny vs huge body.","9-12":"Theropod forelimbs."},"points":1},{"id":"q4","question":"Which animals today are closest to dinosaurs?","question_type":"multiple_choice","options":[{"id":"a","text":"Fish"},{"id":"b","text":"Cats"},{"id":"c","text":"Birds"},{"id":"d","text":"Frogs"}],"correct_answer":"c","explanation":"Birds evolved from theropods!","hints":{"3-5":"Feathers!","6-8":"Feet scales.","9-12":"Theropod-avian lineage."},"points":1}]}', updated_at = datetime('now') WHERE id = 2;

UPDATE lessons SET content_json = '{"type":"sandbox","character":{"name":"Rexy","avatar_key":"","personality":"fun"},"sandbox_type":"sorting","hints":{"3-5":"Tap a dino then tap the bowl!","6-8":"Sort by what they eat!","9-12":"Classify by diet."},"items":[{"id":"trex","label":"T-Rex","correct_zone_id":"carnivore"},{"id":"triceratops","label":"Triceratops","correct_zone_id":"herbivore"},{"id":"brachio","label":"Brachiosaurus","correct_zone_id":"herbivore"},{"id":"raptor","label":"Velociraptor","correct_zone_id":"carnivore"},{"id":"stego","label":"Stegosaurus","correct_zone_id":"herbivore"},{"id":"spino","label":"Spinosaurus","correct_zone_id":"carnivore"}],"zones":[{"id":"herbivore","label":"Plant Eaters","accepts":["triceratops","brachio","stego"]},{"id":"carnivore","label":"Meat Eaters","accepts":["trex","raptor","spino"]}],"completion_criteria":{"type":"all_placed"}}', updated_at = datetime('now') WHERE id = 3;
